services:
  - type: web
    name: da-timer
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT --timeout-keep-alive 75 --timeout-graceful-shutdown 0
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - key: DA_TOKEN
        sync: false   # зададим вручную в панели Render
